# Generated by Django 2.0.8 on 2022-11-17 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('users', models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL, verbose_name='相关用户')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('language_type', models.CharField(blank=True, choices=[('python', 'python'), ('java', 'java'), ('php', 'php'), ('golang', 'golang')], default='', max_length=256, null=True, verbose_name='语言类型')),
                ('repo_url', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='版本库地址')),
                ('jenkins_job', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='JENKINS JOB')),
                ('status', models.CharField(choices=[('0', '启用'), ('1', '停用')], default='0', max_length=2, verbose_name='状态')),
                ('businesses', models.ManyToManyField(blank=True, default='', null=True, to='category.BusinessLine', verbose_name='所属云厂商')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idc', to='category.Idc', verbose_name='业务类型')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='区域类型')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('ssh_ip', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='SSH IP地址/主机名')),
                ('ssh_port', models.IntegerField(blank=True, default=22, max_length=5, null=True, verbose_name='SSH 端口')),
                ('uuid', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='UUID')),
                ('cpu', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='磁盘大小')),
                ('system_product', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='服务器类型')),
                ('daq', models.TextField(blank=True, default='', null=True, verbose_name='数据采集')),
                ('status', models.CharField(choices=[('0', '下线'), ('1', '在线')], default='1', max_length=2, verbose_name='运行状态')),
                ('rack', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='category.Rack', verbose_name='所属业务')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SSHUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('password', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='SSH 密码')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='sshuser',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='category.SSHUser', verbose_name='SSH用户'),
        ),
        migrations.AddField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL, verbose_name='业务相关的用户'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='rack',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='category.Region', verbose_name='区域类型'),
        ),
        migrations.AddField(
            model_name='project',
            name='servers',
            field=models.ManyToManyField(blank=True, default='', null=True, to='category.Server', verbose_name='相关服务器'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL, verbose_name='相关用户'),
        ),
        migrations.AlterUniqueTogether(
            name='idc',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='businessline',
            unique_together={('name',)},
        ),
    ]
