# Generated by Django 2.0.8 on 2022-11-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('name',)},
        ),
    ]
