# Generated by Django 2.0.8 on 2022-11-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='number',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='size',
        ),
        migrations.AddField(
            model_name='server',
            name='region',
            field=models.CharField(choices=[('0', '下线'), ('1', '在线')], default='东区', max_length=200, verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Idc', verbose_name='产品类型'),
        ),
        migrations.AlterField(
            model_name='server',
            name='rack',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='category.Rack', verbose_name='所属业务'),
        ),
    ]
