# Generated by Django 2.0.8 on 2022-11-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20221117_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='address',
        ),
    ]
