# Generated by Django 2.0.8 on 2022-11-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20221115_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
