# Generated by Django 2.0.8 on 2022-11-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_region_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='区域类型'),
        ),
    ]
