# Generated by Django 2.0.8 on 2022-11-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20221115_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='region',
            field=models.CharField(blank=True, choices=[('东区', '东区'), ('南区', '南区'), ('西区', '西区'), ('北区', '北区')], default='', max_length=256, null=True, verbose_name='区域类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='businesses',
            field=models.ManyToManyField(blank=True, default='', null=True, to='category.BusinessLine', verbose_name='所属云厂商'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Idc', verbose_name='业务类型'),
        ),
    ]
