# Generated by Django 2.0.8 on 2022-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20221115_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('address', models.CharField(blank=True, choices=[('东区', '东区'), ('南区', '南区'), ('西区', '西区'), ('北区', '北区')], default='', max_length=256, null=True, verbose_name='区域类型')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name',)},
        ),
    ]
