# Generated by Django 2.0.8 on 2022-11-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20221117_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Idc', verbose_name='业务类型'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Region', verbose_name='区域类型'),
        ),
    ]
