# Generated by Django 2.0.8 on 2022-11-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20221117_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='区域类型'),
        ),
    ]
