# Generated by Django 2.0.8 on 2022-11-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20221117_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='region',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='category.Region', verbose_name='所属区域'),
        ),
    ]
